name: Generate
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # Workaround for https://github.com/nodejs/node-gyp/issues/2219#issuecomment-1359162118
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"
      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "14.x"
      - name: Cache npm dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        run: npm ci
      - name: Generate parser
        run: |
          npx tree-sitter generate
          npx tree-sitter build --wasm -o tree-sitter-elixir.wasm
      - name: Update parser files
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Generate parser
          file_pattern: src
      - name: Checkout gh-pages branch to ./gh-pages
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: gh-pages
          path: ./gh-pages
      - run: mv *.wasm ./gh-pages
      - name: Update WASM file on gh-pages branch
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Generate WASM
          file_pattern: "*.wasm"
          repository: ./gh-pages
